# syntax=docker/dockerfile:1

FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml maven-settings.xml ./

RUN ./mvnw -s ./maven-settings.xml dependency:resolve

COPY src ./src

RUN ./mvnw -s ./maven-settings.xml -DskipTests package

CMD ["./mvnw", "spring-boot:run"]